import type { Metadata } from 'next'

import './globals.css'
import { Footer, Navbar } from '@/components'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-slate-800 text-white px-6'>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
